/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-07-10 07:43:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Random;

public final class fetchdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>piece of cake</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Maven+Pro:400,900,700,500' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- start details -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/productviewgallery.css\" media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cloud-zoom.1.0.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/productviewgallery.js\"></script>\r\n");
      out.write("<!--- start-mmmenu-script---->\r\n");
      out.write("<script src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/jquery.mmenu.all.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.mmenu.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//\tThe menu on the left\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('nav#menu-left').mmenu();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!-- start top_js_button -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
String a=request.getParameter("i");
if(a==null) a="11";
//out.println(a);
Class.forName("com.mysql.jdbc.Driver");

Connection co = DriverManager.getConnection
		("jdbc:mysql://localhost/cakes?user=root&password=stark");

PreparedStatement ps = co.prepareStatement
		("select * from cake5 where id=?");

ps.setString(1,a);

ResultSet rs = ps.executeQuery();

rs.next();

String name=rs.getString(2);
int price=rs.getInt(3);
String des=rs.getString(4);
String img=rs.getString(5);
String imgs="images/smalldynamic/"+img;
String imgl="images/Ldynamic/"+img;

Random rand = new Random(); 
int b=rand.nextInt(16);
//System.out.println(b);
	PreparedStatement ps1 = co.prepareStatement
			("select * from cake5 where id=?");

	ps1.setInt(1,b+1);

	ResultSet rs1 = ps1.executeQuery();

rs1.next();
int id1=b;
String name1=rs1.getString(2);
int price1=rs1.getInt(3);
String des1=rs1.getString(4);
String img1=rs1.getString(5);
String imgs1="images/smalldynamic/"+img1;
String imgl1="images/Ldynamic/"+img1;

b=rand.nextInt(16);
//System.out.println(b);
ps1 = co.prepareStatement
		("select * from cake5 where id=?");

ps1.setInt(1,b+1);

rs1 = ps1.executeQuery();

rs1.next();
int id2=b;
String name2=rs1.getString(2);
int price2=rs1.getInt(3);
String des2=rs1.getString(4);
String img2=rs1.getString(5);
String imgs2="images/smalldynamic/"+img2;
String imgl2="images/Ldynamic/"+img2;

b=rand.nextInt(16);
//System.out.println(b);
ps1 = co.prepareStatement
		("select * from cake5 where id=?");

ps1.setInt(1,b+1);

rs1 = ps1.executeQuery();

rs1.next();
int id3=b;
String name3=rs1.getString(2);
int price3=rs1.getInt(3);
String des3=rs1.getString(4);
String img3=rs1.getString(5);
String imgs3="images/smalldynamic/"+img3;
String imgl3="images/Ldynamic/"+img3;

      out.write("\r\n");
      out.write("<!-- start header -->\r\n");
      out.write("<div class=\"top_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"index.html\"><img src=\"images/cakes/logo (1).jpg\" alt=\"\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <div class=\"log_reg\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.html\">Login</a> </li>\r\n");
      out.write("\t\t\t\t\t<span class=\"log\"> or </span>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register.html\">Register</a> </li>\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"web_search\">\r\n");
      out.write("\t\t \t<form>\r\n");
      out.write("\t\t\t\t<input type=\"text\" value=\"\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '';}\">\r\n");
      out.write("\t\t\t\t<input action=\"product.jsp\" type=\"submit\" value=\" \" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t    </div>\t\t\t\t\t\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start header_btm -->\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"header_btm\">\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"product.jsp\">products</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">about</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">pages</a></li>\r\n");
      out.write("\t\t\t\t<!-- <li><a href=\"blog.html\">blog</a></li> -->\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"smart_nav\">\r\n");
      out.write("\t\t\t<a class=\"navicon\" href=\"#menu-left\"> </a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav id=\"menu-left\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"products.html\">products</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">about</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">pages</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"blog.html\">blog</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t<div class=\"header_right\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i  class=\"art\"></i><span class=\"color1\">30</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i  class=\"cart\"></i><span>0</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start top_bg -->\r\n");
      out.write("<div class=\"top_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"main_top\">\r\n");
      out.write("\t<h2 class=\"style\">our cakes</h2>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start main -->\r\n");
      out.write("<div class=\"main_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t<!-- start content -->\r\n");
      out.write("\t<div class=\"single\">\r\n");
      out.write("\t\t\t<!-- start span1_of_1 -->\r\n");
      out.write("\t\t\t<div class=\"left_content\">\r\n");
      out.write("\t\t\t<div class=\"span1_of_1\">\r\n");
      out.write("\t\t\t\t<!-- start product_slider -->\r\n");
      out.write("\t\t\t\t<div class=\"product-view\">\r\n");
      out.write("\t\t\t\t    <div class=\"product-essential\">\r\n");
      out.write("\t\t\t\t        <div class=\"product-img-box\">\r\n");
      out.write("\t\t\t\t    <div class=\"more-views\">\r\n");
      out.write("\t\t\t\t        <div class=\"more-views-container\">\r\n");
      out.write("\t\t\t\t        <ul>\r\n");
      out.write("\t\t\t\t            <li>\r\n");
      out.write("\t\t\t\t            \t<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\"  href=\"\"  title=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t            \t<img src=\"\" src_main=\"\"  title=\"\" alt=\"\" /></a>            \r\n");
      out.write("\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t            <li>\r\n");
      out.write("\t\t\t\t            \t<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\" href=\"\"  title=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t            \t<img src=\"\" src_main=\"\"  title=\"\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t            <li>\r\n");
      out.write("\t\t\t\t            \t<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\"  href=\"\"  title=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t            \t<img src=\"\" src_main=\"\"  title=\"\" alt=\"\" /></a> \r\n");
      out.write("\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t            <li>\r\n");
      out.write("\t\t\t\t            \t<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\" href=\"\"  title=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t            \t<img src=\"\" src_main=\"\" title=\"\" alt=\"\" /></a>  \r\n");
      out.write("\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t            <li>\r\n");
      out.write("\t\t\t\t            \t<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\"  href=\"\"  title=\"\" alt=\"\">\r\n");
      out.write("\t\t\t\t            \t<img src=\"\" src_main=\"\" title=\"\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t          </ul>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div class=\"product-image\"> \r\n");
      out.write("\t\t\t\t        <a class=\"cs-fancybox-thumbs cloud-zoom\" rel=\"adjustX:30,adjustY:0,position:'right',tint:'#202020',tintOpacity:0.5,smoothMove:2,showTitle:true,titleOpacity:0.5\" data-fancybox-group=\"thumb\" href=");
      out.print(imgl );
      out.write(" title=");
      out.print(name );
      out.write(" alt=");
      out.print(name );
      out.write(">\r\n");
      out.write("\t\t\t\t           \t<img src=");
      out.print(imgl );
      out.write(" alt=");
      out.print(name );
      out.write(" title=");
      out.print(name );
      out.write(" />\r\n");
      out.write("\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("gallery_elmnt = jQblvg('.product-img-box'),\r\n");
      out.write("\t\t\t\t\t\t    galleryObj = new Object(),\r\n");
      out.write("\t\t\t\t\t\t    gallery_conf = new Object();\r\n");
      out.write("\t\t\t\t\t\t    gallery_conf.moreviewitem = '<a class=\"cs-fancybox-thumbs\" data-fancybox-group=\"thumb\"  href=\"\"  title=\"\" alt=\"\"><img src=\"\" src_main=\"\" title=\"\" alt=\"\" /></a>';\r\n");
      out.write("\t\t\t\t\t\t    gallery_conf.animspeed = 200;\r\n");
      out.write("\t\t\t\t\t\tjQblvg(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t    galleryObj[1] = new prodViewGalleryForm(prodGallery, 'prod_1', gallery_elmnt, gallery_conf, '.product-image', '.more-views', 'http:');\r\n");
      out.write("\t\t\t\t\t\t        jQblvg('.product-image .cs-fancybox-thumbs').absoluteClick();\r\n");
      out.write("\t\t\t\t\t\t    jQblvg('.cs-fancybox-thumbs').fancybox({ prevEffect : 'none', \r\n");
      out.write("\t\t\t\t\t\t                             nextEffect : 'none',\r\n");
      out.write("\t\t\t\t\t\t                             closeBtn : true,\r\n");
      out.write("\t\t\t\t\t\t                             arrows : true,\r\n");
      out.write("\t\t\t\t\t\t                             nextClick : true, \r\n");
      out.write("\t\t\t\t\t\t                             helpers: {\r\n");
      out.write("\t\t\t\t\t\t                               thumbs : {\r\n");
      out.write("\t\t\t\t\t\t                                   position: 'bottom'\r\n");
      out.write("\t\t\t\t\t\t                               }\r\n");
      out.write("\t\t\t\t\t\t                             }\r\n");
      out.write("\t\t\t\t\t\t                             });\r\n");
      out.write("\t\t\t\t\t\t    jQblvg('#wrap').css('z-index', '100');\r\n");
      out.write("\t\t\t\t\t\t            jQblvg('.more-views-container').elScroll({type: 'vertical', elqty: 4, btn_pos: 'border', scroll_speed: 400 });\r\n");
      out.write("\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfunction initGallery(a,b,element) {\r\n");
      out.write("\t\t\t\t\t\t    galleryObj[a] = new prodViewGalleryForm(prods, b, gallery_elmnt, gallery_conf, '.product-image', '.more-views', '');\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end product_slider -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- start span1_of_1 -->\r\n");
      out.write("\t\t\t<div class=\"span1_of_1_des\">\r\n");
      out.write("\t\t\t\t  <div class=\"desc1\">\r\n");
      out.write("\t\t\t\t\t<h3>");
      out.print(name );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t<h5>");
      out.print(price );
      out.write(" <span>1099</span>  <a href=\"#\">click for offer</a></h5>\r\n");
      out.write("\t\t\t\t\t<div class=\"available\">\r\n");
      out.write("\t\t\t\t\t\t <div class=\"btn_form\">\r\n");
      out.write("\t\t\t\t\t\t\t <form action=\"#\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"buy now\" title=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <btn><a href=\"#\">buy now</a></btn> -->\r\n");
      out.write("\t\t\t\t\t\t<span><a href=\"#\">login to save in wishlist </a></span>\r\n");
      out.write("\t\t\t\t\t\t<p>It is a long established fact that a reader will be distracted by the readable contentContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from of a page when looking at its layout.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"share-desc\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"share\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Share Product :</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"share_nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/facebook.png\" title=\"facebook\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/twitter.png\" title=\"Twiiter\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/rss.png\" title=\"Rss\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><img src=\"images/gpluse.png\" title=\"Google+\"></a></li>\r\n");
      out.write("\t\t\t\t    \t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t   \t </div>\r\n");
      out.write("\t\t\t   \t</div>\r\n");
      out.write("\t\t\t   \t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t   \t<!-- start left content_bottom -->\r\n");
      out.write("\t\t\t   \t<div class=\"left_content_btm\">\r\n");
      out.write("\t\t\t   \t\t<p class=\"para\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n");
      out.write("\t\t\t   \t\t<!-- start tabs -->\r\n");
      out.write("\t\t\t\t   \t<section class=\"tabs\">\r\n");
      out.write("\t\t            <input id=\"tab-1\" type=\"radio\" name=\"radio-set\" class=\"tab-selector-1\" checked=\"checked\">\r\n");
      out.write("\t\t\t        <label for=\"tab-1\" class=\"tab-label-1\">overview</label>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t            <input id=\"tab-2\" type=\"radio\" name=\"radio-set\" class=\"tab-selector-2\">\r\n");
      out.write("\t\t\t        <label for=\"tab-2\" class=\"tab-label-2\">consumer</label>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t            <input id=\"tab-3\" type=\"radio\" name=\"radio-set\" class=\"tab-selector-3\">\r\n");
      out.write("\t\t\t        <label for=\"tab-3\" class=\"tab-label-3\">semiconductor</label>\r\n");
      out.write("\t          \r\n");
      out.write("\t\t\t\t    <div class=\"clear-shadow\"></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t        <div class=\"content\">\r\n");
      out.write("\t\t\t\t        <div class=\"content-1\">\r\n");
      out.write("\t\t\t\t        \t<p class=\"para top\"><span>LOREM IPSUM</span> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined </p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Research</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Design and Development</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Porting and Optimization</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>System integration</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Verification, Validation and Testing</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Maintenance and Support</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t        <div class=\"content-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"para\"><span>WELCOME </span> Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections </p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"qua_nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Multimedia Systems</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Digital media adapters</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Set top boxes for HDTV and IPTV Player applications on various Operating Systems and Hardware Platforms</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t        <div class=\"content-3\">\r\n");
      out.write("\t\t\t\t        \t<p class=\"para top\"><span>LOREM IPSUM</span> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined </p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Research</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Design and Development</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Porting and Optimization</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>System integration</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Verification, Validation and Testing</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Maintenance and Support</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t        </section>\r\n");
      out.write("\t\t         \t<!-- end tabs -->\r\n");
      out.write("\t\t\t   \t</div>\r\n");
      out.write("\t\t\t   \t<!-- end left content_bottom -->\r\n");
      out.write("\t\t   \t</div>\r\n");
      out.write("\t\t<!-- start left_sidebar -->\r\n");
      out.write("\t\t\t<div class=\"left_sidebar\">\r\n");
      out.write("\t\t\t\t<ul class=\"det_nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">safety and security</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">specials</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">new products</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">safety and security</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<h4>you may also like</h4>\r\n");
      out.write("\t\t\t\t<div class=\"left_products\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left_img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(imgl1 );
      out.write("\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"left_text\">\r\n");
      out.write("\t\t\t\t\t\t<p><a href=\"fetchdetails.jsp?i=");
      out.print(id1);
      out.write('"');
      out.write('>');
      out.print(name1 );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"line\">");
      out.print(price1+200);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print(price1);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"left_products\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left_img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(imgl2 );
      out.write("\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"left_text\">\r\n");
      out.write("\t\t\t\t\t\t<p><a href=\"fetchdetails.jsp?i=");
      out.print(id2);
      out.write('"');
      out.write('>');
      out.print(name2 );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"line\">");
      out.print(price2+500);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print(price2);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"left_products\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left_img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(imgl3 );
      out.write("\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"left_text\">\r\n");
      out.write("\t\t\t\t\t\t<p><a href=\"fetchdetails.jsp?i=");
      out.print(id3);
      out.write('"');
      out.write('>');
      out.print(name3 );
      out.write("</a></p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"line\">");
      out.print(price3+500);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print(price3);
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h4>related colors</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"color-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color2\"> </span><p class=\"red\">Green</p></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color3\"> </span><p class=\"red\">Blue</p></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color4\"> </span><p class=\"red\">Yellow</p></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color5\"> </span><p class=\"red\">Violet</p></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color6\"> </span><p class=\"red\">Orange</p></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"color7\"> </span><p class=\"red\">Gray</p></a></li>\r\n");
      out.write("\t\t\t\t\t   </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("          \t    <div class=\"clear\"></div>\r\n");
      out.write("\t       </div>\t\r\n");
      out.write("\t<!-- end content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_top\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<!-- start grids_of_3 -->\r\n");
      out.write("\t<div class=\"span_of_3\">\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>site developed and maintained by:</h3>\r\n");
      out.write("\t\t\t<p>Ankur Vishwakarma,NIT mizoram</p><br>\r\n");
      out.write("\t\t\t<p>contact: prince.ankur.pv@gmail.com</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>twitter widget</h3>\r\n");
      out.write("\t\t\t<p><a href=\"#\">@Contrarypopular</a> I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give <a href=\"#\">@accountofsystem</a> </p>\r\n");
      out.write("\t\t\t<p class=\"top\">19 days ago</p>\r\n");
      out.write("\t\t\t<p class=\"top\"><a href=\"#\">@Contrarypopular</a> I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give <a href=\"#\">@accountofsystem</a> </p>\r\n");
      out.write("\t\t\t<p class=\"top\">19 days ago</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>flickr widget</h3>\r\n");
      out.write("\t\t\t<ul class=\"f_nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic1.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic2.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic3.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic4.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic5.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic6.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_mid\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"f_search\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<input type=\"text\" value=\"\" placeholder=\"Enter email for newsletter\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"soc_icons\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon1\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon2\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon3\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon4\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon5\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\t<!-- scroll_top_btn -->\r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t  \t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t \t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t <a href=\"#\" id=\"toTop\" style=\"display: block;\"><span id=\"toTopHover\" style=\"opacity: 1;\"></span></a>\r\n");
      out.write("\t\t<!--end scroll_top_btn -->\r\n");
      out.write("\t<div class=\"f_nav1\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">home /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">support /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Terms and conditions /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Faqs /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"copy\">\r\n");
      out.write("\t\t<p class=\"link\"><span>© All rights reserved | Template by&nbsp;<a href=\"http://w3layouts.com/\"> W3Layouts</a></span></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");

co.close();

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
