/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-07-10 12:35:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Random;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>piece of cake</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Maven+Pro:400,900,700,500' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--- start-mmmenu-script---->\r\n");
      out.write("<script src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/jquery.mmenu.all.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.mmenu.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//\tThe menu on the left\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('nav#menu-left').mmenu();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!-- start top_js_button -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
//String a=request.getParameter("i");
//out.println(a);
Class.forName("com.mysql.jdbc.Driver");

Connection co = DriverManager.getConnection
		("jdbc:mysql://localhost/cakes?user=root&password=stark");

PreparedStatement ps = co.prepareStatement
		("select * from cake5");
//int[] price;
int []id=new int[100];
String name[]=new String[100];
int []price=new int[100];
String[] img=new String[100];
String[] des=new String[100];
int i=0;

ResultSet rs = ps.executeQuery();
while(i<10){
	 rs.next();
	 i++;
}
i=0;
//out.println(rs.getInt(1));
while(i<=5){
	rs.next();
	id[i]=rs.getInt(1);
	name[i]=rs.getString(2);
	price[i]=rs.getInt(3);
	des[i]=rs.getString(4);
	img[i]="images/cakes/"+rs.getString(5);
	i++;
}
//for(i=0;i<3;i++) out.println(id[i]);

i=0;
/* String name=rs.getString(2);
int price=rs.getInt(3);
String des=rs.getString(4);
String img=rs.getString(5);
String imgs="images/smalldynamic/"+img;
String imgl="images/Ldynamic/"+img; */


      out.write("\r\n");
      out.write("<!-- start header -->\r\n");
      out.write("<div class=\"top_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"index.html\"><img src=\"images/cakes/logo (1).jpg\" alt=\"\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t <div class=\"log_reg\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.html\">Login</a> </li>\r\n");
      out.write("\t\t\t\t\t<span class=\"log\"> or </span>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register.html\">Register</a> </li>\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"web_search\">\r\n");
      out.write("\t\t \t<form>\r\n");
      out.write("\t\t\t\t<input type=\"text\" value=\"\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = '';}\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\" \" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t    </div>\t\t\t\t\t\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start header_btm -->\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"header_btm\">\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"product.jsp\">products</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">about</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">pages</a></li>\r\n");
      out.write("\t\t\t\t<!-- <li><a href=\"blog.html\">blog</a></li> -->\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"smart_nav\">\r\n");
      out.write("\t\t\t<a class=\"navicon\" href=\"#menu-left\"> </a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<nav id=\"menu-left\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"products.html\">products</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">about</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">pages</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"blog.html\">blog</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t<div class=\"header_right\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i  class=\"art\"></i><span class=\"color1\">30</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i  class=\"cart\"></i><span>0</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start top_bg -->\r\n");
      out.write("<div class=\"top_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"main_top\">\r\n");
      out.write("\t<h2 class=\"style\">our products</h2>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start main -->\r\n");
      out.write("<div class=\"main_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t<div class=\"top_main\">\r\n");
      out.write("\t\t<h2>new arrivals on piece of cake</h2>\r\n");
      out.write("\t\t<a href=\"#\">show all</a>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- start grids_of_3 -->\r\n");
      out.write("\t<div class=\"grids_of_3\">\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i] );
      out.write("</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i+1]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i+1] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i+1] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i+1] );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"price1 bg\">on sale</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i+2]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i+2] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i+2] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i+2] );
      out.write("</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"top_main\">\r\n");
      out.write("\t\t<h2>best sellers of the month</h2>\r\n");
      out.write("\t\t<a href=\"#\">show all</a>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- start grids_of_3 -->\r\n");
      out.write("\t<div class=\"grids_of_3\">\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i+3]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i+3] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i+3] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i+3] );
      out.write("</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i+4]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i+4] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i+4] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i+4] );
      out.write("</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"grid1_of_3\">\r\n");
      out.write("\t\t\t<a href=\"fetchdetails.jsp?i=");
      out.print(id[i+5]);
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=");
      out.print(img[i+5] );
      out.write(" alt=\"\">\r\n");
      out.write("\t\t\t\t<h3>");
      out.print(name[i+5] );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t<span class=\"price\">");
      out.print(price[i+5] );
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"price1 bg1\">out of stock</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<!-- start grids_of_2 -->\r\n");
      out.write("\t<div class=\"grids_of_2\">\r\n");
      out.write("\t\t<div class=\"grid1_of_2\">\r\n");
      out.write("\t\t\t<div class=\"span1_of_2\">\r\n");
      out.write("\t\t\t\t<h2>free shipping</h2>\r\n");
      out.write("\t\t\t\t<p>Lorem Ipsum is simply dummy  typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"span1_of_2\">\r\n");
      out.write("\t\t\t\t<h2>testimonials</h2>\r\n");
      out.write("\t\t\t\t<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using [...]</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"grid1_of_2 bg\">\r\n");
      out.write("\t\t\t<h2>blog news</h2>\r\n");
      out.write("\t\t\t<div class=\"grid_date\">\r\n");
      out.write("\t\t\t\t<div class=\"date1\"> \r\n");
      out.write("\t\t\t\t\t<h4>apr 01</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"date_text\">\r\n");
      out.write("\t\t\t\t\t<h4><a href=\"#\"> Donec vehicula est ac augue consectetur,</a></h4>\r\n");
      out.write("\t\t\t\t\t<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form</p> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"grid_date\">\r\n");
      out.write("\t\t\t\t<div class=\"date1\"> \r\n");
      out.write("\t\t\t\t\t<h4>feb 01</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"date_text\">\r\n");
      out.write("\t\t\t\t\t<h4><a href=\"#\"> The standard chunk of Lorem Ipsum used since ,,</a></h4>\r\n");
      out.write("\t\t\t\t\t<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from </p> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_top\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<!-- start grids_of_3 -->\r\n");
      out.write("\t<div class=\"span_of_3\">\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>site developed and maintained by:</h3>\r\n");
      out.write("\t\t\t<p>Ankur Vishwakarma,NIT mizoram</p><br>\r\n");
      out.write("\t\t\t<p>contact: prince.ankur.pv@gmail.com</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>twitter widget</h3>\r\n");
      out.write("\t\t\t<p><a href=\"#\">@Contrarypopular</a> I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give <a href=\"#\">@accountofsystem</a> </p>\r\n");
      out.write("\t\t\t<p class=\"top\">19 days ago</p>\r\n");
      out.write("\t\t\t<p class=\"top\"><a href=\"#\">@Contrarypopular</a> I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give <a href=\"#\">@accountofsystem</a> </p>\r\n");
      out.write("\t\t\t<p class=\"top\">19 days ago</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"span1_of_3\">\r\n");
      out.write("\t\t\t<h3>flickr widget</h3>\r\n");
      out.write("\t\t\t<ul class=\"f_nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic1.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic2.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic3.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic4.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic5.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><img src=\"images/f_pic6.jpg\" alt=\"\" /> </a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_mid\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"f_search\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<input type=\"text\" value=\"\" placeholder=\"Enter email for newsletter\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"soc_icons\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon1\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon2\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon3\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon4\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"icon5\" href=\"#\"></a></li>\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- start footer -->\r\n");
      out.write("<div class=\"footer_bg\">\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\t<!-- scroll_top_btn -->\r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t  \t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t \t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t <a href=\"#\" id=\"toTop\" style=\"display: block;\"><span id=\"toTopHover\" style=\"opacity: 1;\"></span></a>\r\n");
      out.write("\t\t<!--end scroll_top_btn -->\r\n");
      out.write("\t<div class=\"f_nav1\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\">home /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">support /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Terms and conditions /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Faqs /</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"copy\">\r\n");
      out.write("\t\t<p class=\"link\"><span>© All rights reserved | Template by&nbsp;<a href=\"http://w3layouts.com/\"> W3Layouts</a></span></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
co.close(); 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
